### ISSUE TITLE
Failed to convert wordpress of OCI to Nydus by rafs v6

### ISSUE THREAD

**Issue by ccx1024cc** [dragonflyoss/image-service#1154]
### Version
```shell
# ./nydusify --version
Nydusify version
Version : v2.2.0-59-g6638eee24
Revision        : 6638eee247bb9b56ac03d20b833bf3993a7a9f6b
Go version      : go1.19.7
Build time      : 2023-03-16T14:12:37

# nydus-image --version
Version:        v2.2.0-59-g6638eee24
Git Commit:     6638eee247bb9b56ac03d20b833bf3993a7a9f6b
Build Time:     2023-03-16T03:56:55.572580434Z
Profile:        release
Rustc:          rustc 1.66.1 (90743e729 2023-01-10)
```

### Reproduction
```shell
# ./nydusify convert --source wordpress --target localhost:5077/nydus/wordpress:2.2-v6 --fs-version 6
INFO[2023-03-17T12:07:15+08:00] pulling image docker.io/library/wordpress:latest  module=converter
INFO[2023-03-17T12:07:20+08:00] pulled image docker.io/library/wordpress:latest, elapse 4.387242927s  module=converter
INFO[2023-03-17T12:07:20+08:00] converting image docker.io/library/wordpress:latest  module=converter
INFO[2023-03-17T12:07:20+08:00] [2023-03-17 12:07:20.220508 +08:00] ERROR [/log-panics-2.1.0/src/lib.rs:130] thread 'main' panicked at 'assertion failed: pt.len() * size_of::<u32>() <= prefetch_table_size as usize': rafs/src/builder/core/v6.rs:701  module=builder
INFO[2023-03-17T12:07:20+08:00]    0: backtrace::backtrace::trace             module=builder
INFO[2023-03-17T12:07:20+08:00]    1: backtrace::capture::Backtrace::new      module=builder
INFO[2023-03-17T12:07:20+08:00]                                           module=builder
INFO[2023-03-17T12:07:20+08:00] [2023-03-17 12:07:20.275968 +08:00] ERROR [/log-panics-2.1.0/src/lib.rs:130] thread 'main' panicked at 'assertion failed: pt.len() * size_of::<u32>() <= prefetch_table_size as usize': rafs/src/builder/core/v6.rs:701  module=builder
INFO[2023-03-17T12:07:20+08:00]    0: backtrace::backtrace::trace             module=builder
INFO[2023-03-17T12:07:20+08:00]    1: backtrace::capture::Backtrace::new      module=builder
INFO[2023-03-17T12:07:20+08:00]                                           module=builder
ERRO[2023-03-17T12:07:20+08:00] fail to run nydus-image [create --log-level warn --prefetch-policy fs --blob tmp/nydus-converter-41106729/blob.rafs --whiteout-spec none --fs-version 6 --type tar-rafs --blob-inline-meta --features blob-toc --compressor zstd --chunk-size 0x100000 tmp/nydus-converter-41106729/blob.targz]  error="signal: aborted (core dumped)"
ERRO[2023-03-17T12:07:20+08:00] fail to run nydus-image [create --log-level warn --prefetch-policy fs --blob tmp/nydus-converter-2300640447/blob.rafs --whiteout-spec none --fs-version 6 --type tar-rafs --blob-inline-meta --features blob-toc --compressor zstd --chunk-size 0x100000 tmp/nydus-converter-2300640447/blob.targz]  error="signal: aborted (core dumped)"
FATA[2023-03-17T12:07:33+08:00] convert image: copy nydus blob to content store: failed to copy: convert nydus ref: call builder: signal: aborted (core dumped)
```

**Comment by imeoer** [comment]
Is `6638eee247bb9b56ac03d20b833bf3993a7a9f6b` an upstream commit?

**Comment by jiangliu** [comment]
This is a bug, which breaks the  `Conversion & Check Images` github action, I will take a look at it.
