### ISSUE TITLE
nydusd panic with `virtiofs` subcommand

### ISSUE THREAD

**Issue by flyflypeng** [dragonflyoss/image-service#1194]
I run kata-containers with `virtio-fs-nydus` share_fs configuration, but I failed to create kata-container, I found the the following error info:
```bash
Apr  4 23:30:40 flyflypeng-desktop containerd[426621]: time="2023-04-04T23:30:40.524264122+08:00" level=info msg="starting nydusd" args="virtiofs --hybrid-mode --log-level debug --apisock /run/vc/vm/e2bab3fa84fc6c4677593d1e72ed8d7d5d6dbf105f795911d2085944bf066d82/nydusd-api.sock --sock /run/vc/vm/e2bab3fa84fc6c4677593d1e72ed8d7d5d6dbf105f795911d2085944bf066d82/vhost-fs.sock" name=containerd-shim-v2 path=/usr/local/bin/nydusd pid=491997 sandbox=e2bab3fa84fc6c4677593d1e72ed8d7d5d6dbf105f795911d2085944bf066d82 source=virtcontainers/hypervisor subsystem=nydusd
Apr  4 23:30:40 flyflypeng-desktop kata[491997]: time="2023-04-04T23:30:40.524643152+08:00" level=info msg="nydusd started" args="virtiofs --hybrid-mode --log-level debug --apisock /run/vc/vm/e2bab3fa84fc6c4677593d1e72ed8d7d5d6dbf105f795911d2085944bf066d82/nydusd-api.sock --sock /run/vc/vm/e2bab3fa84fc6c4677593d1e72ed8d7d5d6dbf105f795911d2085944bf066d82/vhost-fs.sock" name=containerd-shim-v2 path=/usr/local/bin/nydusd pid=491997 sandbox=e2bab3fa84fc6c4677593d1e72ed8d7d5d6dbf105f795911d2085944bf066d82 source=virtcontainers/hypervisor subsystem=nydusd
Apr  4 23:30:40 flyflypeng-desktop kata[491997]: time="2023-04-04T23:30:40.524724363+08:00" level=info msg="waiting nydusd API server ready" name=containerd-shim-v2 pid=491997 sandbox=e2bab3fa84fc6c4677593d1e72ed8d7d5d6dbf105f795911d2085944bf066d82 source=virtcontainers/hypervisor subsystem=nydusd
Apr  4 23:30:40 flyflypeng-desktop containerd[426621]: time="2023-04-04T23:30:40.524643152+08:00" level=info msg="nydusd started" args="virtiofs --hybrid-mode --log-level debug --apisock /run/vc/vm/e2bab3fa84fc6c4677593d1e72ed8d7d5d6dbf105f795911d2085944bf066d82/nydusd-api.sock --sock /run/vc/vm/e2bab3fa84fc6c4677593d1e72ed8d7d5d6dbf105f795911d2085944bf066d82/vhost-fs.sock" name=containerd-shim-v2 path=/usr/local/bin/nydusd pid=491997 sandbox=e2bab3fa84fc6c4677593d1e72ed8d7d5d6dbf105f795911d2085944bf066d82 source=virtcontainers/hypervisor subsystem=nydusd
Apr  4 23:30:40 flyflypeng-desktop containerd[426621]: time="2023-04-04T23:30:40.524724363+08:00" level=info msg="waiting nydusd API server ready" name=containerd-shim-v2 pid=491997 sandbox=e2bab3fa84fc6c4677593d1e72ed8d7d5d6dbf105f795911d2085944bf066d82 source=virtcontainers/hypervisor subsystem=nydusd
Apr  4 23:30:40 flyflypeng-desktop kata[491997]: time="2023-04-04T23:30:40.525819838+08:00" level=info msg="[2023-04-04 23:30:40.525776 +08:00] INFO Program Version: v2.2.0, Git Commit: \"a38f6b8d6257af90d59880265335dd55fab07668\", Build Time: \"2023-03-01T10:05:57.267573846Z\", Profile: \"release\", Rustc Version: \"rustc 1.66.1 (90743e729 2023-01-10)\"" name=containerd-shim-v2 pid=491997 sandbox=e2bab3fa84fc6c4677593d1e72ed8d7d5d6dbf105f795911d2085944bf066d82 source=virtcontainers/hypervisor subsystem=nydusd
Apr  4 23:30:40 flyflypeng-desktop kata[491997]: time="2023-04-04T23:30:40.526052786+08:00" level=info msg="[2023-04-04 23:30:40.525812 +08:00] INFO Set rlimit-nofile to 1000000, maximum 1048576" name=containerd-shim-v2 pid=491997 sandbox=e2bab3fa84fc6c4677593d1e72ed8d7d5d6dbf105f795911d2085944bf066d82 source=virtcontainers/hypervisor subsystem=nydusd
Apr  4 23:30:40 flyflypeng-desktop containerd[426621]: time="2023-04-04T23:30:40.525819838+08:00" level=info msg="[2023-04-04 23:30:40.525776 +08:00] INFO Program Version: v2.2.0, Git Commit: \"a38f6b8d6257af90d59880265335dd55fab07668\", Build Time: \"2023-03-01T10:05:57.267573846Z\", Profile: \"release\", Rustc Version: \"rustc 1.66.1 (90743e729 2023-01-10)\"" name=containerd-shim-v2 pid=491997 sandbox=e2bab3fa84fc6c4677593d1e72ed8d7d5d6dbf105f795911d2085944bf066d82 source=virtcontainers/hypervisor subsystem=nydusd
Apr  4 23:30:40 flyflypeng-desktop containerd[426621]: time="2023-04-04T23:30:40.526052786+08:00" level=info msg="[2023-04-04 23:30:40.525812 +08:00] INFO Set rlimit-nofile to 1000000, maximum 1048576" name=containerd-shim-v2 pid=491997 sandbox=e2bab3fa84fc6c4677593d1e72ed8d7d5d6dbf105f795911d2085944bf066d82 source=virtcontainers/hypervisor subsystem=nydusd
Apr  4 23:30:40 flyflypeng-desktop kata[491997]: time="2023-04-04T23:30:40.529728124+08:00" level=info msg="[\x1b[38;5;196m2023-04-04 23:30:40.529683 +08:00\x1b[0m] \x1b[38;5;196mERROR\x1b[0m [/log-panics-2.1.0/src/lib.rs:130] \x1b[38;5;196mthread 'main' panicked at 'ArgAction::SetTrue / ArgAction::SetFalse is defaulted': /cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.0.18/src/parser/matches/arg_matches.rs:174" name=containerd-shim-v2 pid=491997 sandbox=e2bab3fa84fc6c4677593d1e72ed8d7d5d6dbf105f795911d2085944bf066d82 source=virtcontainers/hypervisor subsystem=nydusd
Apr  4 23:30:40 flyflypeng-desktop kata[491997]: time="2023-04-04T23:30:40.529784878+08:00" level=info msg="   0: backtrace::backtrace::trace" name=containerd-shim-v2 pid=491997 sandbox=e2bab3fa84fc6c4677593d1e72ed8d7d5d6dbf105f795911d2085944bf066d82 source=virtcontainers/hypervisor subsystem=nydusd
```

The above log indicates that `nydusd` process started by `containerd-shim-kata-v2` is paniced.

I want to test the whether `parameters` is wrong which is passed from `containerd-shim-kata-v2` to`nydusd`, so I run the
 following command directly under the shell, but get the same panic error info:
```bash
root@flyflypeng-desktop:/home/flyflypeng/tmp# RUST_BACKTRACE=1 nydusd virtiofs --hybrid-mode --log-level debug --apisock /run/vc/vm/e2bab3fa84fc6c4677593d1e72ed8d7d5d6dbf105f795911d2085944bf066d82/nydusd-api.sock --sock /run/vc/vm/e2bab3fa84fc6c4677593d1e72ed8d7d5d6dbf105f795911d2085944bf066d82/vhost-fs.sock
[2023-04-05 00:16:44.855035 +08:00] INFO Program Version: v2.2.0, Git Commit: "a38f6b8d6257af90d59880265335dd55fab07668", Build Time: "2023-03-01T10:05:57.267573846Z", Profile: "release", Rustc Version: "rustc 1.66.1 (90743e729 2023-01-10)"
[2023-04-05 00:16:44.855147 +08:00] INFO Set rlimit-nofile to 1000000, maximum 1000000
[2023-04-05 00:16:44.859073 +08:00] ERROR [/log-panics-2.1.0/src/lib.rs:130] thread 'main' panicked at 'ArgAction::SetTrue / ArgAction::SetFalse is defaulted': /cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.0.18/src/parser/matches/arg_matches.rs:174
   0: backtrace::backtrace::trace
```

nydusd info
```bash
root@flyflypeng-desktop:/home/flyflypeng/tmp# nydusd --version
Version:        v2.2.0
Git Commit:     a38f6b8d6257af90d59880265335dd55fab07668
Build Time:     2023-03-01T10:05:57.267573846Z
Profile:        release
Rustc:          rustc 1.66.1 (90743e729 2023-01-10)
```

**Comment by jiangliu** [comment]
Thanks for reporting, seems like a bug caused by refactor. I will take a look.

**Comment by jiangliu** [comment]
Cherry pick a patch from master to fix this issue: https://github.com/dragonflyoss/image-service/pull/1195
