### ISSUE TITLE
`ctr-remote image rpull` panicked

### ISSUE THREAD

**Issue by liubin** [dragonflyoss/image-service#285]
When running `ctr-remote image rpull --plain-http ghcr.io/dragonflyoss/image-service/alpine:nydus-latest`, it panicked:

```
DEBU[0000] fetching                                      image="ghcr.io/dragonflyoss/image-service/alpine:nydus-latest"
DEBU[0000] resolving                                     host=ghcr.io
DEBU[0000] do request                                    host=ghcr.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=containerd/1.5.8+unknown request.method=HEAD url="https://ghcr.io/v2/dragonflyoss/image-service/alpine/manifests/nydus-latest"
DEBU[0000] fetch response received                       host=ghcr.io response.header.content-length=73 response.header.content-type=application/json response.header.date="Fri, 21 Jan 2022 03:35:37 GMT" response.header.www-authenticate="Bearer realm=\"https://ghcr.io/token\",service=\"ghcr.io\",scope=\"repository:dragonflyoss/image-service/alpine:pull\"" response.header.x-github-request-id="3B5E:0B9B:57103:185732:61EA2A08" response.status="401 Unauthorized" url="https://ghcr.io/v2/dragonflyoss/image-service/alpine/manifests/nydus-latest"
DEBU[0000] Unauthorized                                  header="Bearer realm=\"https://ghcr.io/token\",service=\"ghcr.io\",scope=\"repository:dragonflyoss/image-service/alpine:pull\"" host=ghcr.io
DEBU[0000] do request                                    host=ghcr.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.user-agent=containerd/1.5.8+unknown request.method=HEAD url="https://ghcr.io/v2/dragonflyoss/image-service/alpine/manifests/nydus-latest"
DEBU[0001] fetch response received                       host=ghcr.io response.header.content-length=1052 response.header.content-type=application/vnd.oci.image.manifest.v1+json response.header.date="Fri, 21 Jan 2022 03:35:37 GMT" response.header.docker-content-digest="sha256:6188fc0d382e64fff54f936a9211e20ad6f6839b17171cc3d2faedae2463de9d" response.header.docker-distribution-api-version=registry/2.0 response.header.etag="\"sha256:6188fc0d382e64fff54f936a9211e20ad6f6839b17171cc3d2faedae2463de9d\"" response.header.x-github-request-id="3B5E:0B9B:57106:185737:61EA2A09" response.status="200 OK" url="https://ghcr.io/v2/dragonflyoss/image-service/alpine/manifests/nydus-latest"
DEBU[0001] resolved                                      desc.digest="sha256:6188fc0d382e64fff54f936a9211e20ad6f6839b17171cc3d2faedae2463de9d" host=ghcr.io
fetching sha256:6188fc0d... application/vnd.oci.image.manifest.v1+json
DEBU[0001] fetch                                         digest="sha256:6188fc0d382e64fff54f936a9211e20ad6f6839b17171cc3d2faedae2463de9d" mediatype=application/vnd.oci.image.manifest.v1+json size=1052
DEBU[0001] do request                                    digest="sha256:6188fc0d382e64fff54f936a9211e20ad6f6839b17171cc3d2faedae2463de9d" mediatype=application/vnd.oci.image.manifest.v1+json request.header.accept="application/vnd.oci.image.manifest.v1+json, */*" request.header.user-agent=containerd/1.5.8+unknown request.method=GET size=1052 url="https://ghcr.io/v2/dragonflyoss/image-service/alpine/manifests/sha256:6188fc0d382e64fff54f936a9211e20ad6f6839b17171cc3d2faedae2463de9d"
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f424de1c448]

runtime stack:
runtime.throw(0x1136a33, 0x2a)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:726 +0x4ac

goroutine 16 [syscall]:
runtime.cgocall(0xe67570, 0xc0005345c0, 0xc000010108)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc000534590 sp=0xc000534558 pc=0x4056bb
net._C2func_getaddrinfo(0xc000210400, 0x0, 0xc0003a3e00, 0xc000010108, 0x0, 0x0, 0x0)
	_cgo_gotypes.go:94 +0x55 fp=0xc0005345c0 sp=0xc000534590 pc=0x6093d5
net.cgoLookupIPCNAME.func1(0xc000210400, 0x8, 0x8, 0xc0003a3e00, 0xc000010108, 0x0, 0xc0005346a0, 0x60c8f2)
	/usr/local/go/src/net/cgo_unix.go:161 +0xc5 fp=0xc000534608 sp=0xc0005345c0 pc=0x60f1c5
net.cgoLookupIPCNAME(0x1109705, 0x3, 0xc0002103e0, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/cgo_unix.go:161 +0x16b fp=0xc000534718 sp=0xc000534608 pc=0x60a8eb
net.cgoIPLookup(0xc000278480, 0x1109705, 0x3, 0xc0002103e0, 0x7)
	/usr/local/go/src/net/cgo_unix.go:218 +0x67 fp=0xc0005347b8 sp=0xc000534718 pc=0x60b027
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0005347c0 sp=0xc0005347b8 pc=0x46d581
created by net.cgoLookupIP
	/usr/local/go/src/net/cgo_unix.go:228 +0xc7

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0004a2310)
	/usr/local/go/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc0004a2308)
	/usr/local/go/src/sync/waitgroup.go:130 +0x65
golang.org/x/sync/errgroup.(*Group).Wait(0xc0004a2300, 0xc000188200, 0x12558a0)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:40 +0x31
github.com/containerd/containerd/images.Dispatch(0x1255960, 0xc00008e4e0, 0x1233520, 0xc000460180, 0x0, 0xc000447670, 0x1, 0x1, 0x0, 0xc00044e000)
	/go/pkg/mod/github.com/containerd/containerd@v1.5.8/images/handlers.go:153 +0x1fd
github.com/containerd/containerd.(*Client).fetch(0xc0003b42a0, 0x1255960, 0xc00008e4e0, 0xc000092dd0, 0x7ffd42a80731, 0x36, 0x1, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/containerd/containerd@v1.5.8/pull.go:214 +0x6c5
github.com/containerd/containerd.(*Client).Pull(0xc0003b42a0, 0x1255960, 0xc00008e4e0, 0x7ffd42a80731, 0x36, 0xc0002dddb8, 0x7, 0x7, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/containerd/containerd@v1.5.8/pull.go:92 +0x2e6
github.com/dragonflyoss/image-service/contrib/ctr-remote/commands.pull(0x1255960, 0xc00008e4e0, 0xc0003b42a0, 0x7ffd42a80731, 0x36, 0xc0002ddf98, 0x1255960, 0xc00008e4e0)
	/nydus-rs/contrib/ctr-remote/commands/rpull.go:96 +0x3b2
github.com/dragonflyoss/image-service/contrib/ctr-remote/commands.glob..func1(0xc00013b8c0, 0x0, 0x0)
	/nydus-rs/contrib/ctr-remote/commands/rpull.go:74 +0x1f7
github.com/urfave/cli.HandleAction(0xf9e9c0, 0x115da50, 0xc00013b8c0, 0xc00013b8c0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0xfd
github.com/urfave/cli.Command.Run(0x110ad7c, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1149534, 0x3a, 0x0, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x58e
github.com/urfave/cli.(*App).RunAsSubcommand(0xc000175dc0, 0xc00013b600, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:405 +0x954
github.com/urfave/cli.Command.startApp(0x110be13, 0x6, 0x0, 0x0, 0x17e9940, 0x2, 0x2, 0x1114aff, 0xd, 0x0, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:372 +0x87f
github.com/urfave/cli.Command.Run(0x110be13, 0x6, 0x0, 0x0, 0x17e9940, 0x2, 0x2, 0x1114aff, 0xd, 0x0, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:102 +0x9f4
github.com/urfave/cli.(*App).Run(0xc000175c00, 0xc0000320a0, 0x5, 0x5, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x7e8
main.main()
	/nydus-rs/contrib/ctr-remote/cmd/main.go:60 +0x805

goroutine 6 [select]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc000295980)
	/go/pkg/mod/google.golang.org/grpc@v1.33.2/balancer_conn_wrappers.go:69 +0xc8
created by google.golang.org/grpc.newCCBalancerWrapper
	/go/pkg/mod/google.golang.org/grpc@v1.33.2/balancer_conn_wrappers.go:60 +0x172

goroutine 7 [chan receive]:
google.golang.org/grpc.(*addrConn).resetTransport(0xc0001e18c0)
	/go/pkg/mod/google.golang.org/grpc@v1.33.2/clientconn.go:1188 +0x769
created by google.golang.org/grpc.(*addrConn).connect
	/go/pkg/mod/google.golang.org/grpc@v1.33.2/clientconn.go:825 +0x12a

goroutine 9 [IO wait]:
internal/poll.runtime_pollWait(0x7f424e224f70, 0x72, 0x1233ea0)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc00038a418, 0x72, 0x1233e00, 0x18119c0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00038a400, 0xc0003e4000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc00038a400, 0xc0003e4000, 0x8000, 0x8000, 0x800010601, 0x0, 0x800010601)
	/usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0000106f8, 0xc0003e4000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:182 +0x8e
bufio.(*Reader).Read(0xc0003d2660, 0xc0003b43b8, 0x9, 0x9, 0xc0003e4009, 0xc000080800, 0x0)
	/usr/local/go/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x12313c0, 0xc0003d2660, 0xc0003b43b8, 0x9, 0x9, 0x9, 0x459093, 0x3ad8108d462158, 0xc000541e48)
	/usr/local/go/src/io/io.go:314 +0x87
io.ReadFull(...)
	/usr/local/go/src/io/io.go:333
golang.org/x/net/http2.readFrameHeader(0xc0003b43b8, 0x9, 0x9, 0x12313c0, 0xc0003d2660, 0x0, 0xc072a86200000000, 0x4bbb4dec, 0x186c3c0)
	/go/pkg/mod/golang.org/x/net@v0.0.0-20210226172049-e18ecbb05110/http2/frame.go:237 +0x89
golang.org/x/net/http2.(*Framer).ReadFrame(0xc0003b4380, 0xc0002c7fe0, 0xc0002c7fe0, 0x0, 0x0)
	/go/pkg/mod/golang.org/x/net@v0.0.0-20210226172049-e18ecbb05110/http2/frame.go:492 +0xa5
google.golang.org/grpc/internal/transport.(*http2Client).reader(0xc0003fc000)
	/go/pkg/mod/google.golang.org/grpc@v1.33.2/internal/transport/http2_client.go:1294 +0x179
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/go/pkg/mod/google.golang.org/grpc@v1.33.2/internal/transport/http2_client.go:310 +0x1071

goroutine 10 [select]:
google.golang.org/grpc/internal/transport.(*controlBuffer).get(0xc0002919a0, 0x1, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.33.2/internal/transport/controlbuf.go:395 +0x125
google.golang.org/grpc/internal/transport.(*loopyWriter).run(0xc0003d2780, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.33.2/internal/transport/controlbuf.go:515 +0x1d3
google.golang.org/grpc/internal/transport.newHTTP2Client.func3(0xc0003fc000)
	/go/pkg/mod/google.golang.org/grpc@v1.33.2/internal/transport/http2_client.go:356 +0x7b
created by google.golang.org/grpc/internal/transport.newHTTP2Client
	/go/pkg/mod/google.golang.org/grpc@v1.33.2/internal/transport/http2_client.go:354 +0x123c

goroutine 23 [IO wait]:
internal/poll.runtime_pollWait(0x7f424e224e88, 0x72, 0x1233ea0)
	/usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0000ac218, 0x72, 0x1233e00, 0x18119c0, 0x0)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000ac200, 0xc00017b300, 0x104d, 0x104d, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc0000ac200, 0xc00017b300, 0x104d, 0x104d, 0x203000, 0x6488fb, 0xc0003dc860)
	/usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000010710, 0xc00017b300, 0x104d, 0x104d, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:182 +0x8e
crypto/tls.(*atLeastReader).Read(0xc000218020, 0xc00017b300, 0x104d, 0x104d, 0x1af, 0x1048, 0xc00005b668)
	/usr/local/go/src/crypto/tls/conn.go:779 +0x62
bytes.(*Buffer).ReadFrom(0xc0003dc980, 0x1231540, 0xc000218020, 0x40d365, 0xfef2e0, 0x10dfc80)
	/usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc0003dc700, 0x1232a60, 0xc000010710, 0x5, 0xc000010710, 0x19e)
	/usr/local/go/src/crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc0003dc700, 0x0, 0x0, 0xc0004304e0)
	/usr/local/go/src/crypto/tls/conn.go:608 +0x115
crypto/tls.(*Conn).readRecord(...)
	/usr/local/go/src/crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc0003dc700, 0xc0005de000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1252 +0x15f
net/http.(*persistConn).Read(0xc0000a8fc0, 0xc0005de000, 0x1000, 0x1000, 0xc00005be60, 0x465fc0, 0xc00005be60)
	/usr/local/go/src/net/http/transport.go:1894 +0x77
bufio.(*Reader).fill(0xc0000763c0)
	/usr/local/go/src/bufio/bufio.go:101 +0x105
bufio.(*Reader).Peek(0xc0000763c0, 0x1, 0x2, 0x0, 0x0, 0x0, 0xc000430480)
	/usr/local/go/src/bufio/bufio.go:139 +0x4f
net/http.(*persistConn).readLoop(0xc0000a8fc0)
	/usr/local/go/src/net/http/transport.go:2047 +0x1a8
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1715 +0xcb7

goroutine 24 [select]:
net/http.(*persistConn).writeLoop(0xc0000a8fc0)
	/usr/local/go/src/net/http/transport.go:2346 +0x11c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1716 +0xcdc

goroutine 50 [select]:
net/http.(*Transport).getConn(0xc00046c000, 0xc0000748c0, 0x0, 0xc0001dc000, 0x5, 0xc0002103e0, 0xb, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/http/transport.go:1350 +0x5ac
net/http.(*Transport).roundTrip(0xc00046c000, 0xc0001ba500, 0x30, 0x7f424f2623c0, 0x150)
	/usr/local/go/src/net/http/transport.go:569 +0x7ce
net/http.(*Transport).RoundTrip(0xc00046c000, 0xc0001ba500, 0xc00046c000, 0x0, 0x0)
	/usr/local/go/src/net/http/roundtrip.go:17 +0x35
net/http.send(0xc0001ba500, 0x1232b00, 0xc00046c000, 0x0, 0x0, 0x0, 0xc0000100d0, 0xc000076120, 0x1, 0x0)
	/usr/local/go/src/net/http/client.go:252 +0x453
net/http.(*Client).send(0xc0003a3c80, 0xc0001ba500, 0x0, 0x0, 0x0, 0xc0000100d0, 0x0, 0x1, 0x22c)
	/usr/local/go/src/net/http/client.go:176 +0xff
net/http.(*Client).do(0xc0003a3c80, 0xc0001ba500, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:718 +0x45f
net/http.(*Client).Do(...)
	/usr/local/go/src/net/http/client.go:586
golang.org/x/net/context/ctxhttp.Do(0x1255960, 0xc0003a3920, 0xc0003a3c80, 0xc0001ba400, 0x0, 0x0, 0x1255960)
	/go/pkg/mod/golang.org/x/net@v0.0.0-20210226172049-e18ecbb05110/context/ctxhttp/ctxhttp.go:27 +0x10f
github.com/containerd/containerd/remotes/docker.(*request).do(0xc000186990, 0x1255960, 0xc0001fca80, 0xa03589f80a80f997, 0x11093ae, 0xa00000c0000387b0)
	/go/pkg/mod/github.com/containerd/containerd@v1.5.8/remotes/docker/resolver.go:567 +0x57f
github.com/containerd/containerd/remotes/docker.(*request).doWithRetries(0xc000186990, 0x1255960, 0xc0001fca80, 0x0, 0x0, 0x0, 0x2f, 0x1215276, 0x0)
	/go/pkg/mod/github.com/containerd/containerd@v1.5.8/remotes/docker/resolver.go:576 +0x46
github.com/containerd/containerd/remotes/docker.dockerFetcher.open(0xc00046e000, 0x1255960, 0xc0001fca80, 0xc000186990, 0xc00044c000, 0x2a, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/containerd/containerd@v1.5.8/remotes/docker/fetcher.go:165 +0x22e
github.com/containerd/containerd/remotes/docker.dockerFetcher.Fetch.func1(0x0, 0x67, 0x0, 0x0, 0x7f424f26b378)
	/go/pkg/mod/github.com/containerd/containerd@v1.5.8/remotes/docker/fetcher.go:109 +0xb0f
github.com/containerd/containerd/remotes/docker.(*httpReadSeeker).reader(0xc0004ba6c0, 0x0, 0x7f424c899ec8, 0xc000046e98, 0x0)
	/go/pkg/mod/github.com/containerd/containerd@v1.5.8/remotes/docker/httpreadseeker.go:147 +0x76
github.com/containerd/containerd/remotes/docker.(*httpReadSeeker).Read(0xc0004ba6c0, 0xc000600000, 0x100000, 0x100000, 0xc00020e480, 0x0, 0x0)
	/go/pkg/mod/github.com/containerd/containerd@v1.5.8/remotes/docker/httpreadseeker.go:53 +0x4f
io.ReadAtLeast(0x7f424f26b3c8, 0xc0004ba6c0, 0xc000600000, 0x100000, 0x100000, 0x100000, 0x18a4a28, 0x0, 0x0)
	/usr/local/go/src/io/io.go:314 +0x87
github.com/containerd/containerd/content.copyWithBuffer(0x7f424c75f480, 0xc0004ba640, 0x7f424f26b3c8, 0xc0004ba6c0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/containerd/containerd@v1.5.8/content/helpers.go:262 +0x199
github.com/containerd/containerd/content.Copy(0x1255960, 0xc0004a2360, 0x125b3c0, 0xc0004ba640, 0x7f424f26b3c8, 0xc0004ba6c0, 0x41c, 0xc00044e000, 0x47, 0x0, ...)
	/go/pkg/mod/github.com/containerd/containerd@v1.5.8/content/helpers.go:147 +0x167
github.com/containerd/containerd/remotes.fetch(0x1255960, 0xc0004a2360, 0x7f424c827cd8, 0xc00009a620, 0x1233600, 0xc00046e000, 0xc00044c000, 0x2a, 0xc00044e000, 0x47, ...)
	/go/pkg/mod/github.com/containerd/containerd@v1.5.8/remotes/handlers.go:147 +0x6cd
github.com/containerd/containerd/remotes.FetchHandler.func1(0x12558a0, 0xc0000a2100, 0xc00044c000, 0x2a, 0xc00044e000, 0x47, 0x41c, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/containerd/containerd@v1.5.8/remotes/handlers.go:103 +0x378
github.com/containerd/containerd/images.HandlerFunc.Handle(0xc0004a2270, 0x12558a0, 0xc0000a2100, 0xc00044c000, 0x2a, 0xc00044e000, 0x47, 0x41c, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/containerd/containerd@v1.5.8/images/handlers.go:55 +0x82
github.com/containerd/containerd/images.Handlers.func1(0x12558a0, 0xc0000a2100, 0xc00044c000, 0x2a, 0xc00044e000, 0x47, 0x41c, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/containerd/containerd@v1.5.8/images/handlers.go:65 +0xf8
github.com/containerd/containerd/images.HandlerFunc.Handle(0xc000218100, 0x12558a0, 0xc0000a2100, 0xc00044c000, 0x2a, 0xc00044e000, 0x47, 0x41c, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/containerd/containerd@v1.5.8/images/handlers.go:55 +0x82
github.com/dragonflyoss/image-service/contrib/ctr-remote/commands.appendDefaultLabelsHandlerWrapper.func1.1(0x12558a0, 0xc0000a2100, 0xc00044c000, 0x2a, 0xc00044e000, 0x47, 0x41c, 0x0, 0x0, 0x0, ...)
	/nydus-rs/contrib/ctr-remote/commands/rpull.go:114 +0x96
github.com/containerd/containerd/images.HandlerFunc.Handle(0xc0004a22a0, 0x12558a0, 0xc0000a2100, 0xc00044c000, 0x2a, 0xc00044e000, 0x47, 0x41c, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/containerd/containerd@v1.5.8/images/handlers.go:55 +0x82
github.com/containerd/containerd.(*unpacker).handlerWrapper.func1.1(0x12558a0, 0xc0000a2100, 0xc00044c000, 0x2a, 0xc00044e000, 0x47, 0x41c, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/containerd/containerd@v1.5.8/unpacker.go:304 +0xf6
github.com/containerd/containerd/images.HandlerFunc.Handle(0xc000460180, 0x12558a0, 0xc0000a2100, 0xc00044c000, 0x2a, 0xc00044e000, 0x47, 0x41c, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/containerd/containerd@v1.5.8/images/handlers.go:55 +0x82
github.com/containerd/containerd/images.Dispatch.func1(0x0, 0x0)
	/go/pkg/mod/github.com/containerd/containerd@v1.5.8/images/handlers.go:134 +0xd5
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0004a2300, 0xc000188200)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20201207232520-09787c993a3a/errgroup/errgroup.go:54 +0x66

goroutine 51 [select]:
google.golang.org/grpc.newClientStream.func5(0xc0003dc380, 0xc000124900, 0x1255960, 0xc0004a2480)
	/go/pkg/mod/google.golang.org/grpc@v1.33.2/stream.go:318 +0xda
created by google.golang.org/grpc.newClientStream
	/go/pkg/mod/google.golang.org/grpc@v1.33.2/stream.go:317 +0xbd0

goroutine 14 [select]:
net.(*Resolver).lookupIPAddr(0x186b4c0, 0x1255920, 0xc0002783c0, 0x1109705, 0x3, 0xc0002103e0, 0x7, 0x1bb, 0x0, 0x0, ...)
	/usr/local/go/src/net/lookup.go:299 +0x685
net.(*Resolver).internetAddrList(0x186b4c0, 0x1255920, 0xc0002783c0, 0x1109705, 0x3, 0xc0002103e0, 0xb, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/ipsock.go:280 +0x4d4
net.(*Resolver).resolveAddrList(0x186b4c0, 0x1255920, 0xc0002783c0, 0x1109c57, 0x4, 0x1109705, 0x3, 0xc0002103e0, 0xb, 0x0, ...)
	/usr/local/go/src/net/dial.go:221 +0x47d
net.(*Dialer).DialContext(0xc0004600c0, 0x1255960, 0xc0003a3920, 0x1109705, 0x3, 0xc0002103e0, 0xb, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dial.go:403 +0x22b
net/http.(*Transport).dial(0xc00046c000, 0x1255960, 0xc0003a3920, 0x1109705, 0x3, 0xc0002103e0, 0xb, 0x0, 0x1, 0xffffffffffffffff, ...)
	/usr/local/go/src/net/http/transport.go:1144 +0x1fd
net/http.(*Transport).dialConn(0xc00046c000, 0x1255960, 0xc0003a3920, 0x0, 0xc0001dc000, 0x5, 0xc0002103e0, 0xb, 0x0, 0xc0001e3560, ...)
	/usr/local/go/src/net/http/transport.go:1582 +0x1adb
net/http.(*Transport).dialConnFor(0xc00046c000, 0xc0000da370)
	/usr/local/go/src/net/http/transport.go:1424 +0xc6
created by net/http.(*Transport).queueForDial
	/usr/local/go/src/net/http/transport.go:1393 +0x40f

goroutine 15 [select]:
net.cgoLookupIP(0x12558a0, 0xc000074940, 0x1109705, 0x3, 0xc0002103e0, 0x7, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/cgo_unix.go:229 +0x199
net.(*Resolver).lookupIP(0x186b4c0, 0x12558a0, 0xc000074940, 0x1109705, 0x3, 0xc0002103e0, 0x7, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/lookup_unix.go:96 +0x187
net.glob..func1(0x12558a0, 0xc000074940, 0xc00023e7b0, 0x1109705, 0x3, 0xc0002103e0, 0x7, 0xc0003a3920, 0x0, 0xc0001dc000, ...)
	/usr/local/go/src/net/hook.go:23 +0x72
net.(*Resolver).lookupIPAddr.func1(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/lookup.go:293 +0xb9
internal/singleflight.(*Group).doCall(0x186b4d0, 0xc00052e230, 0xc0002103f0, 0xb, 0xc000074980)
	/usr/local/go/src/internal/singleflight/singleflight.go:95 +0x2e
created by internal/singleflight.(*Group).DoChan
	/usr/local/go/src/internal/singleflight/singleflight.go:88 +0x2cc
```

**Comment by changweige** [comment]
Hi @liubin 
I guess we already solved this issue offline, right?

**Comment by liubin** [comment]
This can be closed
