### ISSUE TITLE
nydusctl --sock $s info cause nydusd-virtiofs panicked

### ISSUE THREAD

**Issue by liubin** [dragonflyoss/image-service#294]
`nydusctl --sock $s info` cause `nydusd-virtiofs` crashed:

> Jan 29 16:27:09 kant-server kata[30906]: time="2022-01-29T16:27:09.824797412+08:00" level=info msg="[2022-01-29 16:27:09.824650 +08:00] INFO [api/src/http.rs:97] <--- Get Uri { string: \"/api/v1/daemon\" }" name=containerd-shim-v2 pid=30906 sandbox=ae63a1205ada600b6fab254b19fc3cf277ec6da15e37877cfeba23ff69758509 source=virtcontainers/hypervisor subsystem=nydusd
Jan 29 16:27:09 kant-server kata[30906]: time="2022-01-29T16:27:09.826984021+08:00" level=info msg="thread 'main' panicked at 'not implemented', src/bin/nydusd/virtiofs.rs:311:9" name=containerd-shim-v2 pid=30906 sandbox=ae63a1205ada600b6fab254b19fc3cf277ec6da15e37877cfeba23ff69758509 source=virtcontainers/hypervisor subsystem=nydusd
Jan 29 16:27:09 kant-server containerd[27056]: time="2022-01-29T16:27:09.826984021+08:00" level=info msg="thread 'main' panicked at 'not implemented', src/bin/nydusd/virtiofs.rs:311:9" name=containerd-shim-v2 pid=30906 sandbox=ae63a1205ada600b6fab254b19fc3cf277ec6da15e37877cfeba23ff69758509 source=virtcontainers/hypervisor subsystem=nydusd
Jan 29 16:27:09 kant-server containerd[27056]: time="2022-01-29T16:27:09.827125911+08:00" level=info msg="note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace" name=containerd-shim-v2 pid=30906 sandbox=ae63a1205ada600b6fab254b19fc3cf277ec6da15e37877cfeba23ff69758509 source=virtcontainers/hypervisor subsystem=nydusd
Jan 29 16:27:09 kant-server kata[30906]: time="2022-01-29T16:27:09.827125911+08:00" level=info msg="note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace" name=containerd-shim-v2 pid=30906 sandbox=ae63a1205ada600b6fab254b19fc3cf277ec6da15e37877cfeba23ff69758509 source=virtcontainers/hypervisor subsystem=nydusd

For these APIs, returning HTTP status code 501 will be better than crashing the daemon process.
Or just implement them.

**Comment by liubin** [comment]
If having backends, will get this error:

```bash
$ nydusctl --sock $sock info

Version:                "2.0.0-rc.0"
Status:                 "RUNNING"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected struct RafsConfig", line: 0, column: 0)', src/bin/nydusctl/commands.rs:344:89
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)

```

Using curl get daemon directly:

```bash
$ curl -s --unix-socket $sock     -H "Content-Type: application/json"     -H "accept: */*"     -X GET http://localhost/api/v1/daemon | jq .
```

```json
{
  "version": {
    "package_ver": "2.0.0-rc.0",
    "git_commit": "64ca2ca7b9bc2c5e7c8766b16cebb91ea5bf4918",
    "build_time": "Sun, 30 Jan 2022 05:04:22 +0000",
    "profile": "debug",
    "rustc": "rustc 1.58.1 (db9d1b20b 2022-01-20)"
  },
  "id": null,
  "supervisor": null,
  "state": "RUNNING",
  "backend_collection": {
    "/containers": {
      "backend_type": "PassthroughFs",
      "mountpoint": "/containers",
      "mounted_time": "2022-01-30 13:09:12.534633732 +08:00",
      "config": null
    }
  }
}

```

virtiofs will have a null config item.
