### ISSUE TITLE
Nydus-test found an error during executing fscache mode test

### ISSUE THREAD

**Issue by changweige** [dragonflyoss/image-service#693]
The test image is exactly the same with fuse mode nydusd while fuse mode can pass the case

kernel info:
```
Linux n227-089-202 5.19.0-rc4 #2 SMP PREEMPT_DYNAMIC Thu Jun 30 17:33:40 CST 2022 x86_64 GNU/Linux

```

```
[2022-08-23 09:21:25,948] ERROR [workload_gen - 457:io_read] - Stress read failure, [Errno 5] Input/output error
Traceback (most recent call last):
  File "/data00/home/gechangwei/git_repo/nydus-rs/contrib/nydus-test/framework/workload_gen.py", line 454, in io_read
    cnt, size, duration = self.read_collected_files(io_duration)
  File "/data00/home/gechangwei/git_repo/nydus-rs/contrib/nydus-test/framework/workload_gen.py", line 417, in read_collected_files
    raise exc
  File "/data00/home/gechangwei/git_repo/nydus-rs/contrib/nydus-test/framework/workload_gen.py", line 411, in read_collected_files
    buf = f.read(io_size)
OSError: [Errno 5] Input/output error
[2022-08-23 09:21:26.115574 +08:00] ERROR [error/src/error.rs:21] Error:
	"entry not found index 215 infos.len 216"
	at storage/src/meta/mod.rs:492
	note: enable `RUST_BACKTRACE=1` env to display a backtrace
[2022-08-23 09:21:26.115631 +08:00] ERROR [src/bin/nydusd/fs_cache.rs:707] fscache: failed to read data from blob object: Invalid argument (os error 22)
[2022-08-23 09:21:26.117981 +08:00] ERROR [error/src/error.rs:21] Error:
	"entry not found index 215 infos.len 216"
	at storage/src/meta/mod.rs:492
	note: enable `RUST_BACKTRACE=1` env to display a backtrace
[2022-08-23 09:21:26.118024 +08:00] ERROR [src/bin/nydusd/fs_cache.rs:707] fscache: failed to read data from blob object: Invalid argument (os error 22)
[2022-08-23 09:21:26,120] ERROR [workload_gen - 415:read_collected_files] - file /data00/home/gechangwei/nydus-test-yard/rafs_mnt/DIR.0.1/DIR.1.1/DIR.2.4/DIR.3.2/DIR.4.0/DfxkrGkkjXoCCH.regular, offset 16621, io size 1048576
[2022-08-23 09:21:26,120] ERROR [workload_gen - 457:io_read] - Stress read failure, [Errno 5] Input/output error
Traceback (most recent call last):
  File "/data00/home/gechangwei/git_repo/nydus-rs/contrib/nydus-test/framework/workload_gen.py", line 454, in io_read
    cnt, size, duration = self.read_collected_files(io_duration)
  File "/data00/home/gechangwei/git_repo/nydus-rs/contrib/nydus-test/framework/workload_gen.py", line 417, in read_collected_files
    raise exc
  File "/data00/home/gechangwei/git_repo/nydus-rs/contrib/nydus-test/framework/workload_gen.py", line 411, in read_collected_files
    buf = f.read(io_size)
OSError: [Errno 5] Input/output error
[2022-08-23 09:21:26.152824 +08:00] ERROR [error/src/error.rs:21] Error:
	"entry not found index 215 infos.len 216"
	at storage/src/meta/mod.rs:492
	note: enable `RUST_BACKTRACE=1` env to display a backtrace
[2022-08-23 09:21:26.152883 +08:00] ERROR [src/bin/nydusd/fs_cache.rs:707] fscache: failed to read data from blob object: Invalid argument (os error 22)
[2022-08-23 09:21:26,155] ERROR [workload_gen - 415:read_collected_files] - file /data00/home/gechangwei/nydus-test-yard/rafs_mnt/DIR.0.1/DIR.1.1/DIR.2.4/DIR.3.2/DIR.4.0/DfxkrGkkjXoCCH.regular, offset 77436, io size 3145728
[2022-08-23 09:21:26,155] ERROR [workload_gen - 457:io_read] - Stress read failure, [Errno 5] Input/output error
Traceback (most recent call last):
  File "/data00/home/gechangwei/git_repo/nydus-rs/contrib/nydus-test/framework/workload_gen.py", line 454, in io_read
    cnt, size, duration = self.read_collected_files(io_duration)
  File "/data00/home/gechangwei/git_repo/nydus-rs/contrib/nydus-test/framework/workload_gen.py", line 417, in read_collected_files
    raise exc
  File "/data00/home/gechangwei/git_repo/nydus-rs/contrib/nydus-test/framework/workload_gen.py", line 411, in read_collected_files
    buf = f.read(io_size)

```

**Comment by changweige** [comment]
The issue is closed so fast 🥶. The PR still needs more discussion
